[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_list_app = "4MaTQUzeDHpRCbQpm1CvNQ7JWkwqFH9L2qbqRxBaZTfw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bprime/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
